apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "arbeidssokerregistrering-for-veileder-demo"
  namespace: "paw"
  labels:
    "team": "paw"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/isalive"
    initialDelay: 3
  readiness:
    path: "/api/isready"
    initialDelay: 3
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  env:
    - name: SELF_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no
    - name: DEKORATOR_URL
      value: https://dekoratoren.ekstern.dev.nav.no/
    - name: DEKORATOR_ENV
      value: dev
    - name: NEXT_PUBLIC_SELF_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no
    - name: NEXT_PUBLIC_AMPLITUDE_API_KEY
      value: 9845ded64c69cd068651cd0d968e0796
    - name: NEXT_PUBLIC_AMPLITUDE_ENDPOINT
      value: amplitude.nav.no/collect
    - name: NEXT_PUBLIC_ENABLE_MOCK
      value: enabled
    - name: NEXT_PUBLIC_DITTNAV_URL
      value: https://www.nav.no/minside
    - name: NEXT_PUBLIC_DAGPENGESOKNAD_URL
      value: https://www.nav.no/dagpenger/dialog/soknad
    - name: NEXT_PUBLIC_DIALOG_URL
      value: https://www.nav.no/arbeid/dialog
    - name: NEXT_PUBLIC_MER_OPPFOLGING_URL
      value: https://demo.ekstern.dev.nav.no/syk/meroppfolging/reg/0
    - name: PAM_JANZZ_URL
      value: https://arbeidsplassen.nav.no/pam-janzz/rest
    - name: START_REGISTRERING_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/startregistrering
    - name: FULLFOR_REGISTRERING_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/fullforregistrering
    - name: FULLFOR_REGISTRERING_SYKMELDT_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/fullforregistreringsykmeldt
    - name: REAKTIVERING_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/reaktivering
    - name: SISTE_ARBEIDSFORHOLD_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/sistearbeidsforhold
    - name: OPPRETT_OPPGAVE_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/oppgave
    - name: KONTAKTINFORMASJON_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/kontaktinformasjon
    - name: FEATURE_TOGGLE_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/features
    - name: NODE_ENV
      value: development
    - name: HENT_PROFILERING_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/profilering
    - name: MODIACONTEXTHOLDER_URL
      value: https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no/api/mocks/modiacontextholder
    - name: NAIS_CLUSTER_NAME
      value: dev-gcp
  ingresses:
    - https://arbeidssokerregistrering-for-veileder.ekstern.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: arbeidsplassen.nav.no
        - host: arbeid.ekstern.dev.nav.no
        - host: paw-unleash-api.nav.cloud.nais.io
