export const REGLER_SOM_IKKE_KAN_OVERSTYRES = [
    'UKJENT_REGEL',
    'IKKE_FUNNET',
    'DOED',
    'SAVNET',
    'ANSATT_IKKE_TILGANG_TIL_BRUKER',
];

export const REGLER_SOM_KAN_OVERSTYRES = [
    'UNDER_18_AAR',
    'UKJENT_ALDER',
    'IKKE_BOSATT_I_NORGE_I_HENHOLD_TIL_FOLKEREGISTERLOVEN',
    'ER_EU_EOES_STATSBORGER_MED_STATUS_IKKE_BOSATT',
];
