/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/v2/bekreftelser': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Hent alle bekreftelser for oppgitte perioder */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description https://www.w3.org/TR/trace-context/#traceparent-header-field-values */
                    traceparent?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        perioder: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description Trace id */
                        'x-trace-id'?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['BekreftelserResponse'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/v2/tidslinjer': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Hent alle bekreftelser for oppgitte perioder */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description https://www.w3.org/TR/trace-context/#traceparent-header-field-values */
                    traceparent?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        perioder: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description Trace id */
                        'x-trace-id'?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['TidslinjeResponse'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description En periode er en tidsperiode hvor en bruker har vært registrert som arbeidssøker.
         *     En bruker kan ha flere perioder, og en periode kan være pågående eller avsluttet.
         *     En periode er pågående dersom "avsluttet" er 'null' (ikke satt).
         *      */
        Periode: {
            /**
             * Format: uuid
             * @description Unik identifikator for perioden.
             *     Annen data knyttet til perioden kan lagres i andre systemer med denne som nøkkel.
             *     Opplysninger som hentes inn fra arbeidssøkeren vil være knyttet til denne perioden,
             *     det samme gjelder profileringsresultater.
             *
             */
            id: string;
            /** @description Inneholder informasjon om hvem perioden tilhører (fødselsnummer eller d-nummer) */
            identitetsnummer: string;
            /** @description Inneholder informasjon om når perioden startet og hvem som startet den */
            startet: components['schemas']['Metadata'];
            /** @description Dersom det er en pågående periode, vil denne være 'null'. Er den ikke 'null', er perioden avsluttet.
             *     Inneholder informasjon om når perioden ble avsluttet og hvem som avsluttet den
             *      */
            avsluttet?: components['schemas']['Metadata'];
        };
        /** @description Inneholder metadata om en endring i arbeidssøkerregisteret. */
        Metadata: {
            /**
             * Format: date-time
             * @description Tidspunkt for endringen.
             */
            tidspunkt: string;
            utfoertAv: components['schemas']['Bruker'];
            /** @description Navn på systemet som utførte endringen eller ble benyttet til å utføre endringen. */
            kilde: string;
            /** @description Aarasek til endringen. Feks "Flyttet ut av landet" eller lignende. */
            aarsak: string;
            /** @description Avvik i tid mellom kilde og register. */
            tidspunktFraKilde?: components['schemas']['TidspunktFraKilde'];
        };
        /** @description Informasjon om brukeren som utførte en handling */
        Bruker: {
            /**
             * @description Type bruker som utførte handlingen
             * @enum {string}
             */
            type: 'UKJENT_VERDI' | 'UDEFINERT' | 'VEILEDER' | 'SYSTEM' | 'SLUTTBRUKER';
            /** @description Identifikator for brukeren, format avhenger av brukertype */
            id: string;
            /** @description Sikkerhetsnivået bruker var innlogget med ved utførelse av handlingen */
            sikkerhetsnivaa?: string;
        };
        TidspunktFraKilde: {
            /**
             * Format: date-time
             * @description Betydningen av tidspunktet er avhengig av avviksType.
             *     FORSINKELSE: Tidspunktet er tidspunktet da endringen skulle vært utført.
             *
             *     SLETTET: Tidspunktet er tidspunktet da endringen ble utført(samme som selve recorden).
             *
             *     TIDSPUNKT_KORRIGERT: Tidspunktet som egentlig er korrekt, feks tidspunktet da en periode skulle vært stoppet
             *                        eller startet
             *
             */
            tidspunkt: string;
            /** @description Årsaken til til avvik i tid mellom kilde og register. */
            avviksType: components['schemas']['AvviksType'];
        };
        /**
         * @description Ukjent verdi settes aldri direkte, men brukes som standardverdi og
         *     for å indikere at en verdi er ukjent for mottaker av melding, dvs at
         *     at den er satt til en verdi som ikke er definert i Avro-skjemaet til mottaker.
         *
         * @default UKJENT_VERDI
         * @enum {string}
         */
        AvviksType: 'UKJENT_VERDI' | 'FORSINKELSE' | 'RETTING' | 'SLETTET' | 'TIDSPUNKT_KORRIGERT';
        OpplysningerOmArbeidssoeker: {
            /**
             * Format: uuid
             * @description Unik identifikator for opplysningene.
             */
            id: string;
            /**
             * Format: uuid
             * @description Id for perioden opplysningene tilhører.
             */
            periodeId: string;
            sendtInnAv: components['schemas']['Metadata'];
            utdanning?: components['schemas']['Utdanning'];
            helse?: components['schemas']['Helse'];
            jobbsituasjon?: components['schemas']['Jobbsituasjon'];
            annet?: components['schemas']['Annet'];
        };
        /** @description Information about the job seeker's education background */
        Utdanning: {
            /** @description NUS kode for utdanning, oversikt over NUS koder er tilgjengelig fra SSB.
             *      */
            nus: string;
            /** @description Bare inkludert dersom informasjonen er innhetet, feks for
             *     nus kode 0,1,2 og 9 gir det ikke mening å hente inn info for
             *     dette feltet.
             *      */
            bestaatt?: components['schemas']['JaNeiVetIkke'];
            /** @description Bare inkludert dersom informasjonen er innhetet, feks for
             *     nus kode 0,1,2 og 9 gir det ikke mening å hente inn info for
             *     dette feltet.
             *      */
            godkjent?: components['schemas']['JaNeiVetIkke'];
        };
        /**
         * @description UKJENT_VERDI - Verdien er satt, men den er ikke definert i versjonen av APIet som klienten bruker.
         *     JA - Ja.
         *     NEI - Nei.
         *     VET_IKKE - Vet ikke.
         *
         * @default UKJENT_VERDI
         * @enum {string}
         */
        JaNeiVetIkke: 'UKJENT_VERDI' | 'JA' | 'NEI' | 'VET_IKKE';
        /** @description Har personen helseutfordringer som hindrer dem i å jobbe? */
        Helse: {
            helsetilstandHindrerArbeid?: components['schemas']['JaNeiVetIkke'];
        };
        /** @description Inneholder et sett med beskrivelser av jobbsituasjonen. Det er mulig å ha flere beskrivelser av jobbsituasjonen,
         *     feks kan personen være permittert og samtidig ha en deltidsjobb.
         *      */
        Jobbsituasjon: {
            beskrivelser: components['schemas']['BeskrivelseMedDetaljer'][];
        };
        /** @description Beskrivelse av et enkelt forhold som inngår i jobbsituasjonen, feks permitering eller oppsigelse */
        BeskrivelseMedDetaljer: {
            beskrivelse: components['schemas']['Beskrivelse'];
            /** @description Feltene taes bare med dersom de er er tilgjengelige, i praksis må klienter støtte å motta en tom map.
             *     Andre felter enn de som er definert her kan også forekomme.
             *     Detaljer om jobbsituasjonen. Følgende nøkler er definert:
             *             Nøkkel                      -           Verdi
             *     gjelder_fra_dato_iso8601    -       datoen jobbsituasjonen gjelder fra (eksempel 2019-01-27)
             *     gjelder_til_dato_iso8601    -       datoen jobbsituasjonen gjelder til (eksempel 2019-01-27)
             *     stilling_styrk08            -       stillingens kode i STYRK08 (eksempel "2359"), se SSB for mer informasjon om STYRK08.
             *                                         Forventet for:
             *                                         - HAR_SAGT_OPP
             *                                         - HAR_BLITT_SAGT_OPP
             *                                         - PERMITTERT
             *                                         - KONKURS
             *                                         Kan også brukes for andre beskriverlser som er knyttet til en stilling, feks "DELTIDSJOBB_VIL_MER"
             *     prosent                     -       prosentandel jobbstituasjonen gjelder for (feks kombinert med 'ER_PERMITTERT' eller 'DELTIDSJOBB_VIL_MER'), eksempel "50".
             *     siste_dag_med_loenn_iso8601 -       Siste dag det betales lønn for (feks ved oppsigelse)(eksempel 2019-01-27).
             *                                         Enkelte kilder, inkludert migrering har brukt 'siste_dag_med_loen_iso8601' (en 'n'), enbefaler
             *                                         derfor å normalisere til 'siste_dag_med_loenn_iso8601' (to 'n') ved lesing for å fange begge verianter.
             *     siste_arbeidsdag_iso8601    -       Siste arbeidssdag. Ikke nødvendigvis siste dag det betales lønn for, feks ved konkurs(eksempel 2019-01-27).
             *      */
            detaljer: {
                [key: string]: string;
            };
        };
        /**
         * @description Beskrivelse av jobbsituasjonen. Følgende beskrivelser er definert:
         *     UKJENT_VERDI                    -       Verdien er satt, men den er ikke definert i versjonen av APIet som klienten bruker.
         *     UDEFINERT                       -       Verdien er ikke satt.
         *     HAR_SAGT_OPP                    -       Personen har sagt opp sin stilling.
         *     HAR_BLITT_SAGT_OPP              -       Personen har blitt sagt opp fra sin stilling.
         *     ER_PERMITTERT                   -       Personen er permittert.
         *     ALDRI_HATT_JOBB                 -       Personen har aldri hatt en jobb.
         *     IKKE_VAERT_I_JOBB_SISTE_2_AAR   -       Personen har ikke vært i jobb de siste 2 årene.
         *     AKKURAT_FULLFORT_UTDANNING      -       Personen har akkurat fullført sin utdanning.
         *     USIKKER_JOBBSITUASJON           -       Personen er usikker på sin jobbsituasjon.
         *     MIDLERTIDIG_JOBB                -       Personen har en midlertidig jobb.
         *     DELTIDSJOBB_VIL_MER             -       Personen har en/flere deltidsjobber, men ønsker å jobbe mer.
         *     NY_JOBB                         -       Personen har fått seg ny jobb.
         *     KONKURS                         -       Personen har mistet jobben på grunn av konkurs.
         *     ANNET                           -       Personen har en annen jobbsituasjon.
         *
         * @default UKJENT_VERDI
         * @enum {string}
         */
        Beskrivelse:
            | 'UKJENT_VERDI'
            | 'UDEFINERT'
            | 'HAR_SAGT_OPP'
            | 'HAR_BLITT_SAGT_OPP'
            | 'ER_PERMITTERT'
            | 'ALDRI_HATT_JOBB'
            | 'IKKE_VAERT_I_JOBB_SISTE_2_AAR'
            | 'AKKURAT_FULLFORT_UTDANNING'
            | 'VIL_BYTTE_JOBB'
            | 'USIKKER_JOBBSITUASJON'
            | 'MIDLERTIDIG_JOBB'
            | 'DELTIDSJOBB_VIL_MER'
            | 'NY_JOBB'
            | 'KONKURS'
            | 'ANNET';
        /** @description Har personen andre forhold som hindrer dem i å jobbe? */
        Annet: {
            andreForholdHindrerArbeid?: components['schemas']['JaNeiVetIkke'];
        };
        /** @description Profilering av arbeidssøker
         *     Inneholder informasjon som brukes til ruting av arbeidssøker til riktig veiledningstjeneste.
         *     Profileringen er koblet til et bestemt sett opplysninger om arbeidssøker og en bestemt periode.
         *     I tilfeller hvor 'opplysningerOmAbreidssøker' oppdateres til å gjelde periode vil det dukke opp en ny
         *     profilering knyttet til den samme 'opplysningerOmArbeidssokerId' (periodeId vil være endret).
         *      */
        Profilering: {
            /**
             * Format: uuid
             * @description Unik id for profileringen
             */
            id: string;
            /**
             * Format: uuid
             * @description Unik id for perioden som profileringen tilhører
             */
            periodeId: string;
            /**
             * Format: uuid
             * @description Unik id for OpplysningerOmArbeidssøker som profileringen tilhører
             */
            opplysningerOmArbeidssokerId: string;
            /** @description Inneholder informasjon om når profileringen ble opprettet.
             *     Profileringen er en automatisk prosess så 'sendtInnAv.utfoertAv' vil alltid peke på en
             *     'SYSTEM' bruker med id på formen '[APP_NAVN]:[VERSJON]'
             *      */
            sendtInnAv: components['schemas']['Metadata'];
            /** @description Selve profileringsresultatet */
            profilertTil: components['schemas']['ProfilertTil'];
            /** @description Om personen har jobbet sammenhengende seks av de siste tolv månedene */
            jobbetSammenhengendeSeksAvTolvSisteMnd: boolean;
            /** @description Personens alder */
            alder?: number | null;
        };
        /**
         * @description Resultatet av en profilering
         *     UKJENT_VERDI - Verdien er satt, men den er ikke definert i versjonen av APIet som klienten bruker.
         *     UDEFINERT - Ingen verdi er satt.
         *     ANTATT_GODE_MULIGHETER - Antatt gode muligheter for å komme i arbeid.
         *     ANTATT_BEHOV_FOR_VEILEDNING - Antatt behov for veiledning.
         *     OPPGITT_HINDRINGER - Personen har oppgitt at det finnes hindringer (helse eller annet) for å komme i arbeid.
         *
         * @default UKJENT_VERDI
         * @enum {string}
         */
        ProfilertTil:
            | 'UKJENT_VERDI'
            | 'UDEFINERT'
            | 'ANTATT_GODE_MULIGHETER'
            | 'ANTATT_BEHOV_FOR_VEILEDNING'
            | 'OPPGITT_HINDRINGER';
        /** @description Bekreftelse melding */
        Bekreftelse: {
            /**
             * Format: uuid
             * @description UUID for perioden som meldingen gjelder, hentes fra Periode topic eller oppslags api.
             */
            periodeId: string;
            /** @description Hvilket løsning/system som sender meldingen. */
            bekreftelsesloesning: components['schemas']['Bekreftelsesloesning'];
            /**
             * Format: uuid
             * @description Unik id for meldingen. Duplikater sees på som nettverkshikke eller lignende og skal trygt kunne ignoreres.
             */
            id: string;
            /** @description Svar fra bruker, inkludert metadata. */
            svar: components['schemas']['Svar'];
        };
        /**
         * @default UKJENT_VERDI
         * @enum {string}
         */
        Bekreftelsesloesning:
            | 'UKJENT_VERDI'
            | 'ARBEIDSSOEKERREGISTERET'
            | 'DAGPENGER'
            | 'FRISKMELDT_TIL_ARBEIDSFORMIDLING';
        Svar: {
            sendtInnAv: components['schemas']['Metadata'];
            /** Format: date-time */
            gjelderFra: string;
            /** Format: date-time */
            gjelderTil: string;
            harJobbetIDennePerioden: boolean;
            vilFortsetteSomArbeidssoeker: boolean;
        };
        PaaVegneAvStart: {
            /**
             * Format: uuid
             * @description UUID for perioden som meldingen gjelder, hentes fra Periode topic eller oppslags api.
             */
            periodeId: string;
            /** @description Hvilket løsning/system som sender meldingen. */
            bekreftelsesloesning: components['schemas']['Bekreftelsesloesning'];
            /**
             * Format: int64
             * @description Interval for bekreftelse i millisekunder. Denne gir registeret et hint om hvor ofte løsningen vil sende meldinger, registeret vil ikke gjøre noe når fristen utløper.
             *
             */
            intervalMS: number;
            /**
             * Format: int64
             * @description Grace periode i millisekunder. Hvor lenge den som sender bekreftelse på vegne av arbeidssøker venter etter at intervallet er utløpt før den terminerer sine tjenester og stopper bekreftelse på vegne av arbeidssøker. Feks før dagpengene stoppes og og dagpengeløsningen stopper bekreftelse på vegne av arbeidssøker. Dette brukes av registeret for å å kunne oppdage 'døde' klienter, men har ingen funksjonell betydning.
             *
             */
            graceMS: number;
        };
        PaaVegneAvStopp: {
            /**
             * Format: uuid
             * @description UUID for perioden som meldingen gjelder, hentes fra Periode topic eller oppslags api.
             */
            periodeId: string;
            /** @description Hvilket løsning/system som sender meldingen. */
            bekreftelsesloesning: components['schemas']['Bekreftelsesloesning'];
            /**
             * @description Angir om grunnen til stopp meldingen er at brukeren har brutt fristen i det eksterne systemet. Dersom denne er satt til true og fristene som ble meldt inn i start meldingen er like eller lenger enn registerets egne frister vil arbeidssøkerperioden bli stoppet umidelbart.
             *
             * @default false
             */
            fristBrutt: boolean;
        };
        BekreftelseMedMetadata: {
            /**
             * @description Angir om dette er en gyldig bekreftelse
             * @enum {string}
             */
            status?: 'GYLDIG' | 'UVENTET_KILDE' | 'UTENFOR_PERIODE';
            bekreftelse?: components['schemas']['Bekreftelse'];
        };
        /** @description Response for bekreftelser */
        BekreftelserResponse: {
            bekreftelser: components['schemas']['BekreftelseMedMetadata'][];
        };
        /** @enum {string} */
        HendelseType:
            | 'periode_startet_v1'
            | 'periode_avsluttet_v1'
            | 'opplysninger_v4'
            | 'profilering_v1'
            | 'bekreftelse_v1'
            | 'pa_vegne_av_start_v1'
            | 'pa_vegne_av_stopp_v1';
        /** @description En hendelse i tidslinjen for en periode */
        Hendelse: {
            /** @description Angir hvilken hendelse dette er, som angir hvilken type data som er inkludert */
            hendelseType: components['schemas']['HendelseType'];
            /**
             * Format: date-time
             * @description Tidspunktet for hendelsen
             */
            tidspunkt: string;
            periode_startet_v1?: components['schemas']['Metadata'];
            periode_avsluttet_v1?: components['schemas']['Metadata'];
            opplysninger_v4?: components['schemas']['OpplysningerOmArbeidssoeker'];
            profilering_v1?: components['schemas']['Profilering'];
            bekreftelse_v1?: components['schemas']['BekreftelseMedMetadata'];
            pa_vegne_av_start_v1?: components['schemas']['PaaVegneAvStart'];
            pa_vegne_av_stopp_v1?: components['schemas']['PaaVegneAvStopp'];
        };
        /** @description Tidslinje for en Arbeidssøkerperiode */
        Tidslinje: {
            /**
             * Format: uuid
             * @description UUID for perioden som tidslinjen gjelder
             */
            periodeId: string;
            /** @description Identitetsnummer for arbeidssøker, fødselsnummer eller d-nummer */
            identitetsnummer: string;
            /**
             * Format: date-time
             * @description Starttidspunkt for perioden
             */
            startet: string;
            /**
             * Format: date-time
             * @description Avslutningstidspunkt for perioden, ikke satt dersom perioden er pågående
             */
            avsluttet?: string;
            hendelser: components['schemas']['Hendelse'][];
        };
        /** @description Response for tidslinjekall */
        TidslinjeResponse: {
            tidslinjer?: components['schemas']['Tidslinje'][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
