apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "arbeidssokerregistrering-for-veileder"
  namespace: "paw"
  labels:
    "team": "paw"
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/isalive"
    initialDelay: 3
  readiness:
    path: "/api/isready"
    initialDelay: 3
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: SELF_URL
      value: https://arbeidssokerregistrering-for-veileder.intern.nav.no
    - name: DEKORATOR_URL
      value: https://dekoratoren.nav.no/
    - name: DEKORATOR_ENV
      value: prod
    - name: NEXT_PUBLIC_SELF_URL
      value: https://arbeidssokerregistrering-for-veileder.intern.nav.no
    - name: NEXT_PUBLIC_AMPLITUDE_API_KEY
      value: 913768927b84cde5eac0d0d18c737561
    - name: NEXT_PUBLIC_AMPLITUDE_ENDPOINT
      value: https://amplitude.nav.no/collect
    - name: NEXT_PUBLIC_ENABLE_MOCK
      value: disabled
    - name: ENABLE_MOCK
      value: disabled
    - name: NEXT_PUBLIC_DITTNAV_URL
      value: https://www.nav.no/minside
    - name: NEXT_PUBLIC_DAGPENGESOKNAD_URL
      value: https://arbeid.nav.no/dagpenger/dialog/soknad
    - name: NEXT_PUBLIC_DIALOG_URL
      value: https://www.nav.no/arbeid/dialog
    - name: PAM_JANZZ_URL
      value: https://arbeidsplassen.nav.no/pam-janzz/rest
    - name: PAM_ONTOLOGI_URL
      value: https://pam-ontologi.intern.nav.no/rest/
    - name: NODE_ENV
      value: production
    - name: HENT_PROFILERING_URL
      value: http://veilarbregistrering/veilarbregistrering/api/profilering/
    - name: UNLEASH_SERVER_API_URL
      value: https://paw-unleash-api.nav.cloud.nais.io/api
    - name: ARBEIDSSOKER_PERIODER_URL
      value: http://veilarbregistrering/veilarbregistrering/api/arbeidssoker/perioder/niva3
    - name: MODIACONTEXTHOLDER_URL
      value: https://modiacontextholder.intern.nav.no
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: prod-gcp.personoversikt.modiacontextholder
    - name: INTERNARBEIDSFLATEDEKORATOR_URL
      value: https://internarbeidsflatedecorator.prod-fss-pub.nais.io
    - name: NEXT_PUBLIC_ASSET_PREFIX
      value: https://cdn.nav.no/paw/arbeidssokerregistrering-for-veileder
    - name: DECORATOR_URL
      value: https://internarbeidsflatedecorator.intern.nav.no
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.poao/veilarboppfolging
    - name: VEILARBDIALOG_URL
      value: http://veilarbdialog.dab/veilarbdialog
    - name: VEILARBPERSON_URL
      value: http://veilarbperson.obo/veilarbperson
    - name: VEILARBVEILEDER_URL
      value: https://veilarbveileder.prod-fss-pub.nais.io/veilarbveileder
    - name: OBO_UNLEASH_URL
      value: http://obo-unleash.obo.svc.cluster.local
    - name: AAREG_REST_API
      value: https://aareg-services.prod-fss-pub.nais.io/api
    - name: AAREG_CLUSTER
      value: prod-fss
    - name: AAREG_APPNAME
      value: aareg-services-nais
    - name: INNGANG_API_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
    - name: OPPLYSNINGER_API_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
    - name: OPPSLAG_API_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag
    - name: AIA_BACKEND_URL
      value: http://aia-backend/aia-backend
    - name: BEKREFTELSE_API_URL
      value: http://paw-arbeidssoekerregisteret-api-bekreftelse
  envFrom:
    - secret: poa-arbeidssokerregistrering-veileder-unleash-api-token
  ingresses:
    - https://arbeidssokerregistrering-for-veileder.intern.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: arbeidsplassen.nav.no
        - host: pam-ontologi.intern.nav.no
        - host: paw-unleash-api.nav.cloud.nais.io
        - host: modiacontextholder.intern.nav.no
        - host: internarbeidsflatedecorator.prod-fss-pub.nais.io
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: veilarbdialog.prod-fss-pub.nais.io
        - host: veilarbperson.prod-fss-pub.nais.io
        - host: veilarbveileder.prod-fss-pub.nais.io
        - host: veilarbvisittkortfs.intern.nav.no
        - host: aareg-services.prod-fss-pub.nais.io
      rules:
        - application: paw-arbeidssokerregisteret-api-inngang
        - application: paw-arbeidssoekerregisteret-api-oppslag
        - application: aia-backend
        - application: paw-arbeidssoker-besvarelse
        - application: paw-arbeidssoekerregisteret-api-bekreftelse
        - application: modiacontextholder
          namespace: personoversikt
        - application: veilarboppfolging
          namespace: poao
          cluster: prod-gcp
        - application: veilarbdialog
          namespace: dab
          cluster: prod-gcp
        - application: veilarbperson
          namespace: obo
          cluster: prod-gcp
        - application: veilarbveileder
          namespace: pto
          cluster: prod-fss
        - application: obo-unleash
          namespace: obo
          cluster: prod-gcp
        - application: aareg-services-nais
          namespace: arbeidsforhold
          cluster: prod-fss
