apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "arbeidssokerregistrering-for-veileder"
  namespace: "paw"
  labels:
    "team": "paw"
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/isalive"
    initialDelay: 3
  readiness:
    path: "/api/isready"
    initialDelay: 3
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  prometheus:
    enabled: false
  resources:
    limits:
      memory: "384Mi"
    requests:
      cpu: "50m"
      memory: "256Mi"
  env:
    - name: SELF_URL
      value: https://arbeidssokerregistrering-for-veileder.intern.nav.no
    - name: DEKORATOR_ENV
      value: prod
    - name: NEXT_PUBLIC_ENABLE_MOCK
      value: disabled
    - name: ENABLE_MOCK
      value: disabled
    - name: PAM_ONTOLOGI_URL
      value: http://pam-ontologi.teampam/rest
    - name: NODE_ENV
      value: production
    - name: UNLEASH_SERVER_API_URL
      value: https://paw-unleash-api.nav.cloud.nais.io/api
    - name: MODIACONTEXTHOLDER_URL
      value: https://modiacontextholder.intern.nav.no
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: prod-gcp.personoversikt.modiacontextholder
    - name: NEXT_PUBLIC_ASSET_PREFIX
      value: https://cdn.nav.no/paw/arbeidssokerregistrering-for-veileder
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.poao/veilarboppfolging
    - name: VEILARBDIALOG_URL
      value: http://veilarbdialog.dab/veilarbdialog
    - name: VEILARBPERSON_URL
      value: http://veilarbperson.obo/veilarbperson
    - name: VEILARBVEILEDER_URL
      value: http://veilarbveileder.obo/veilarbveileder
    - name: VEILARBVEDTAKSSTOTTE_URL
      value: http://veilarbvedtaksstotte.obo/veilarbvedtaksstotte
    - name: OBO_UNLEASH_URL
      value: http://obo-unleash.obo.svc.cluster.local
    - name: AAREG_REST_API
      value: https://aareg-services.prod-fss-pub.nais.io/api
    - name: AAREG_CLUSTER
      value: prod-fss
    - name: AAREG_APPNAME
      value: aareg-services-nais
    - name: INNGANG_API_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
    - name: OPPLYSNINGER_API_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
    - name: OPPSLAG_API_V2_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag-v2
    - name: BEKREFTELSE_API_URL
      value: http://paw-arbeidssoekerregisteret-api-bekreftelse
    - name: NEXT_PUBLIC_UMAMI_TRACKING_ID
      value: ec13193d-a5b2-4ec1-a0e5-1bd4c798a9b3
  envFrom:
    - secret: poa-arbeidssokerregistrering-veileder-unleash-api-token
  ingresses:
    - https://arbeidssokerregistrering-for-veileder.intern.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: paw-unleash-api.nav.cloud.nais.io
        - host: umami.nav.no
        - host: modiacontextholder.intern.nav.no
        - host: internarbeidsflatedecorator.prod-fss-pub.nais.io
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: veilarbdialog.prod-fss-pub.nais.io
        - host: veilarbperson.prod-fss-pub.nais.io
        - host: veilarbvisittkortfs.intern.nav.no
        - host: aareg-services.prod-fss-pub.nais.io
        - host: cdn.nav.no
      rules:
        - application: paw-arbeidssokerregisteret-api-inngang
        - application: paw-arbeidssoekerregisteret-api-oppslag-v2
        - application: paw-arbeidssoekerregisteret-api-bekreftelse
        - application: modiacontextholder
          namespace: personoversikt
        - application: veilarboppfolging
          namespace: poao
          cluster: prod-gcp
        - application: pam-ontologi
          namespace: teampam
        - application: veilarbdialog
          namespace: dab
          cluster: prod-gcp
        - application: veilarbperson
          namespace: obo
          cluster: prod-gcp
        - application: veilarbveileder
          namespace: obo
          cluster: prod-gcp
        - application: obo-unleash
          namespace: obo
          cluster: prod-gcp
        - application: veilarbvedtaksstotte
          namespace: obo
          cluster: prod-gcp
        - application: aareg-services-nais
          namespace: arbeidsforhold
          cluster: prod-fss
