name: Build, push, and deploy

on:
    push:
        branches:
            - main
            - dev/*

jobs:
    test-and-build-cdn-docker:
        name: Run tests, build, push assets to CDN and publish Docker image
        runs-on: ubuntu-latest
        timeout-minutes: 7
        permissions:
            contents: 'read'
            packages: 'write'
            id-token: 'write'

        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  persist-credentials: false

            - name: Set up pnpm
              uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
              with:
                  run_install: false

            - name: Set up node
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: '24.13.0'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@navikt'

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
              id: pnpm-cache

            - name: Setup pnpm cache
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm i --frozen-lockfile --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

            - name: Test
              run: pnpm run test:ci

            - name: Knip
              run: pnpm exec knip --no-exit-code --reporter=markdown >> "$GITHUB_STEP_SUMMARY"

            - name: Build
              run: pnpm run build
              env:
                  NODE_ENV: production
                  NEXT_PUBLIC_ASSET_PREFIX: https://cdn.nav.no/paw/arbeidssokerregistrering-for-veileder

            - name: Upload static files to NAV CDN
              uses: nais/deploy/actions/cdn-upload/v2@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # v2
              with:
                  team: paw
                  source: ./.next/static
                  destination: arbeidssokerregistrering-for-veileder/_next
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

            - name: docker-build-push
              uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # v0
              id: docker-build-push
              with:
                  team: paw
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
        outputs:
            image: ${{ steps.docker-build-push.outputs.image }}

    deploy-dev:
        name: Deploy to dev
        permissions:
            contents: 'read'
            id-token: 'write'
        needs: [test-and-build-cdn-docker, apply-apitoken-unleash]
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
        runs-on: ubuntu-latest
        timeout-minutes: 7
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  persist-credentials: false
            - name: Deploy
              uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # v2
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/dev-gcp/nais.yaml
                  VAR: image=${{ needs.test-and-build-cdn-docker.outputs.image }}

    deploy-demo:
        name: Deploy to demo
        permissions:
            contents: 'read'
            id-token: 'write'
        needs: [test-and-build-cdn-docker]
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
        runs-on: ubuntu-latest
        timeout-minutes: 7
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  persist-credentials: false
            - name: Deploy
              uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # v2
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/demo.yaml
                  VAR: image=${{ needs.test-and-build-cdn-docker.outputs.image }}

    deploy-prod:
        name: Deploy to prod
        permissions:
            contents: 'read'
            id-token: 'write'
        needs: [test-and-build-cdn-docker, apply-apitoken-unleash]
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        timeout-minutes: 7
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  persist-credentials: false
            - name: Deploy
              uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # v2
              env:
                  CLUSTER: prod-gcp
                  RESOURCE: .nais/prod-gcp/nais.yaml
                  VAR: image=${{ needs.test-and-build-cdn-docker.outputs.image }}

    apply-apitoken-unleash:
        name: Legger til ApiToken for Unleash
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        timeout-minutes: 7
        needs: [test-and-build-cdn-docker]
        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  persist-credentials: false
            - name: deploy to dev
              uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # v2
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/dev-gcp/unleash-apitoken.yaml
            - name: deploy to prod
              uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # v2
              env:
                  CLUSTER: prod-gcp
                  RESOURCE: .nais/prod-gcp/unleash-apitoken.yaml
